# Generated by Django 5.0.1 on 2024-01-20 17:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0002_alter_category_options_blog'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='slog',
            new_name='slug',
        ),
    ]
